# Generated by Django 5.1.1 on 2024-10-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0004_contact_resume_personaldata_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
