# Generated by Django 5.1.1 on 2024-10-27 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0005_alter_personaldata_id_alter_personaldata_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicformation',
            old_name='addictional_formations',
            new_name='additional_formations',
        ),
        migrations.RenameField(
            model_name='academicformation',
            old_name='curse',
            new_name='course',
        ),
    ]
