# Generated by Django 5.1.1 on 2024-10-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0006_rename_addictional_formations_academicformation_additional_formations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldata',
            old_name='genero',
            new_name='gender',
        ),
    ]
