# Generated by Django 5.1.1 on 2024-10-29 21:05

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0007_rename_genero_personaldata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicformation',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(null=False),
        ),
    ]
