# Generated by Django 5.1.1 on 2024-10-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='Nome Padrão', max_length=100),
        ),
    ]
